config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  resources :blogs
  resources :dogs
  resources :perfumes
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]


  resources :dogs do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'dogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/models/dog.rb
class Dog < ApplicationRecord
    belongs_to :user 
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    #dogsテーブルから中間テーブルに対する関連付け
    has_many :dog_tag_relations, dependent: :destroy
    #dogsテーブルから中間テーブルを介してTagsテーブルへの関連付け
    has_many :tags, through: :dog_tag_relations, dependent: :destroy
    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader
end

app/models/dog_tag_relation.rb
class DogTagRelation < ApplicationRecord
  belongs_to :dog
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :dog
  belongs_to :user
  validates_uniqueness_of :dog_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :dog_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :dogs, through: :dog_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :dogs, dependent: :destroy
         validates :name, presence: true
         validates :profile, length: { maximum: 200 }
         has_many :likes, dependent: :destroy
         has_many :liked_dogs, through: :likes, source: :dog
         has_many :comments, dependent: :destroy
         def already_liked?(dog)
          self.likes.exists?(dog_id: dog.id)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end


def new
  @blog = Blog.new
end

def show
  @blog = Blog.find(params[:id])
end

def create
  Blog.create(blog_parameter)
  redirect_to blogs_path
end

def destroy
  @blog = Blog.find(params[:id])
  @blog.destroy
  redirect_to blogs_path, notice:"削除しました"
end

def edit
  @blog = Blog.find(params[:id])
end

def update
  @blog = Blog.find(params[:id])
  if @blog.update(blog_parameter)
    redirect_to blogs_path, notice: "編集しました"
  else
    render 'edit'
  end
end

private

def blog_parameter
  params.require(:blog).permit(:title, :content, :start_time)
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    dog = Dog.find(params[:dog_id])
    comment = dog.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) 
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index 
        if params[:search] == nil  
          @dogs=Dog.all
        elsif params[:search] == ''
          @dogs=Dog.all
        else
          #部分検索
          @dogs = Dog.where("body LIKE ? ",'%' + params[:search] + '%')
        end

        @blogs = Blog.all

        @perfume = Perfume.new

        if params[:tag_ids]
          @dogs = []
          params[:tag_ids].each do |key, value|      
            if value == "1"
              tag_dogs = Tag.find_by(name: key).dogs
              @dogs = @dogs.empty? ? tag_dogs : @dogs & tag_dogs
            end
          end
        end 
        
        if params[:tag]
          Tag.create(name: params[:tag])
        end
    end

    def new
        @dog = Dog.new
    end
    
    def create
        dog = Dog.new(dog_params)
        dog.user_id = current_user.id 
        if dog.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @dog = Dog.find(params[:id])
        @comments = @dog.comments
        @comment = Comment.new
    end

    def edit
        @dog = Dog.find(params[:id])
    end

    def update
        dog = Dog.find(params[:id])
      if dog.update(dog_params)
          redirect_to :action => "show", :id => dog.id
        else
          redirect_to :action => "new"
      end
    end

    def destroy
        dog = Dog.find(params[:id])
        dog.destroy
        redirect_to action: :index
    end

    def calender
      @blogs = Blog.all
    end
    
      private
    def dog_params
        params.require(:dog).permit(:body,:image,:title, :content, :start_time,:youtube_url, tag_ids: [])
    end


  end 

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(dog_id: params[:dog_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(dog_id: params[:dog_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end
  
    def new
      @perfume = Perfume.new
    end
  
    def show
      @perfume = Perfume.find_by(id: params[:id])
    end
  
    def create
      @perfume = Perfume.new(perfume_params)
      params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
      if @perfume.save
          flash[:notice] = "診断が完了しました"
          redirect_to perfume_path(@perfume.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def perfume_params
        params.require(:perfume).permit(:id, question: [])
    end
  end
  
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
    def find_youtube_url(youtube_url)
        if youtube_url[0..16] == "https://youtu.be/"
          return youtube_url[17..27]
          # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        else
          return youtube_url[32..42]
          # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
      <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>
  
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
  <% end %>
  

app/views/blogs/index.html.erb
<h1>Blogs#index</h1>
<p>Find me in app/views/blogs/index.html.erb</p>

<p id="notice"><%= notice %></p>

<h1>自分の日記</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog.id) %></td>
        <td><%= link_to 'Destroy',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記をかく', new_blog_path %>

<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
      <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>
  
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
  <% end %>
  

app/views/blogs/show.html.erb
<div class="zoo">
<p id="notice"><%= notice %></p>
<br>
<p>
  
  <%= @blog.title %>
</p>
<br>

<p>
  
  <br>
  <div class="blog">
  <%= @blog.content %>
  </div>
</p>

</div>

<div class="finish">
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>


</div>

app/views/dogs/calender.html.erb
<h1>Blogs#index</h1>
<p>Find me in app/views/blogs/index.html.erb</p>

<p id="notice"><%= notice %></p>

<h1>自分の日記</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog.id) %></td>
        <td><%= link_to 'Destroy',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記をかく', new_blog_path %>

<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>

app/views/dogs/index.html.erb




<div class="slide">

<%= image_tag 'スライド1.jpg', class:'tea'  %>
<%= image_tag 'スライド2.jpg', class:'tea'  %>
<%= image_tag 'スライド3.jpg', class:'tea'  %>

  
</div>

<div class="salt">


<div class="suger">

<h4>Search🔍</h4>

 <%= form_tag({controller:"dogs",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

</div>

</div>


<div class="box">

<p><h3>About</h3></p>
<p><h4>ありのままを大切にします。</h4>
<br>
<h4>Happy Herbs🌿は、ヨガとアロマセラピーを通じて暮らしを調和させ,
お客様の心と身体にゆとりを提供し、幸せを届けるサイトです。ヨガを通してお体のお悩みを解決し、またヨガのマインドと触れることでマインドフルネスを目指します。ヨガとアロマを日常に取り入れることでひとりでも多くのお客様に元気と幸せをお届けできれば幸いです。</h4>
<br>
<h4>詳細はこちら</h4></p>

</div>

<div class="cat">
<h4>--おすすめ--</h4>
</div>

<div class="spring">

 <div class="summer">
 <h4>ポーズ一覧</h4>
 <br>
 <h4>体の悩みを選択することでおすすめのポーズを紹介します</h4>
 </div>


 <%= image_tag 'ヨガポーズ一覧.jpg', class:'yoga' %>
 
</div>

<div class="spring">

 <div class="sun">

 <%= image_tag 'ヨガ哲学.jpg', class:'yoga' %>
 
 </div>

 <div class="summer">
 <h4>ヨガ哲学</h4>
 <br>
 <h4>一日一ヨガ哲学でマインドフルネスを目指しましょう</h4>
 </div>

</div>

<div class="spring">

<div class="summer">
<h4>今週のおすすめ</h4>
</div>

<%=image_tag '今週.jpg', class:'yoga' %>
</div>

<div class="spring">

<div class="sun">
<%=image_tag 'アロマ.jpg', class:'yoga' %>
</div>

<div class="summer">
<h4>おすすめのアロマ</h4>
</div>

</div>

<div class="cat">
<h4>--記事を探す--</h4>
</div>

<div class="cloud">



<div class="pig">
  <div class="fish">
<h4>カラダのヨガ</h4>
  </div>

  <div class="fish">
<h4>心のヨガ</h4>
  </div>
</div>

<div class="pig">
  <div class="fish">
<h4>生活のヨガ</h4>
  </div>

<div class="fish">
<h4>ヨガについて</h4>
  </div>
</div>

<div class="pig">
  <div class="fish">
<h4>アロマ一覧</h4>
</div>

<div class="fish">
<h4>生活とアロマ</h4>
  </div>
</div>

 </div>
</div>

<div class="cat">
<h4>--お悩みから検索--</h4>
</div>

<div class="dogs-container">

<br>
<div class="moon">
<h4>タグ1➝腰痛</h4>
<h4>タグ2➝頭痛</h4>
<h4>タグ3➝むくみ</h4>
<h4>タグ4➝ダイエット</h4>
<h4>タグ5➝肩こり</h4>
</div>

<br>

<div class="tag">

<%= form_tag({controller:"dogs",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <%= submit_tag '検索' %>
<% end %>

<%= form_tag({controller:"dogs",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

</div>


  <% @dogs.each do |t| %>
    <div class="dog">

     <div class="main-box">
      <div class="left-container">

       <%= image_tag t.image_url, size: "250x200" if t.image? %>

       <% if t.youtube_url.present? %>
       <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
       <% end %>


       <%= t.user.email %>
       <%= t.body %>

       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
       <%= link_to dog_like_path(id: t.id, dog_id: t.id), method: :delete do %>
       <i class="fas fa-heart"></i><%= t.likes.count %>   
       <% end %>

       <% else %>
       <%= link_to dog_likes_path(id: t.id, dog_id: t.id), method: :post do %>
       <i class="far fa-heart"></i><%= t.likes.count %>
       <% end %>
       <% end %>

       <% else %>
       <i class="far fa-heart"></i><%= t.likes.count %>
       <% end %>
     </div>

     <div class="right-container">

      <%= link_to "詳細へ", dog_path(t.id) %> 

      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_dog_path(t.id) %>
      <%= button_to "削除する", dog_path(t.id), method: :delete %>
     </div>
       
     <% end %> 

     </div>
      <p class="time"><%= t.created_at %></p>
     </div>
     <% end %>
   </div>

<div class="cat">
<h4>--あなたのアロマ🌿--</h4>
</div>


<div class="note">

   <!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
   <html lang="ja"><!--言語の指定-->
       <head><!--ページに表示されない情報(サイトの裏側の設定)-->
           <meta charset="utf-8">
           <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
       </head>
   
       <body>
           
       <h4>  あなたに合うアロマ診断をしてみよう！</h4>
       <br>
           <div class="start">
               <%= link_to "診断を始める！", new_perfume_path, class: "link" %>
               
           </div>
           <br>
           <br>
       </body>

  </div>
  </div>

<div class="cat">
<h4>--今日のマインドフルネス--</h4>
</div>

    
<div class="grass">
  
  <%= link_to '今日の一言', new_blog_path %>
  
  <%= month_calendar events: @blogs do |date, blogs| %>
    <%= date.day %>
  
    <% blogs.each do |blog| %>
      <div>
        <%= link_to blog.title, blog %>
      </div>
    <% end %>
  <% end %>

</div>

<div class="finish">

<div class="word">

<ul>
    <% if user_signed_in? %>
     <li><%= link_to "〇ログアウト",new_dog_path %></li>
     <br>
     <br>
     <li><%= link_to "〇マイページへ", user_path(current_user.id) %></li>
     <br>
     <br>
     <li><%= link_to "〇新規投稿",new_dog_path %></li>
     <br>
     <br>
     <li><%= link_to "〇ポーズ紹介",new_dog_path %></li>
     <br>
     <br>
     <li><%= link_to "〇今日のマインドフルネス",new_dog_path %></li>
     <br>
     <br>
     <li><%= link_to "〇今週のおすすめ",new_dog_path %></li>
     <br>
     <br>
     <li><%= link_to "〇診断機能",new_dog_path %></li>
     <br>
     <br>
    <% else %>
     <li><%= link_to "〇新規登録", new_user_registration_path %></li>
     <li><%= link_to "〇ログイン", new_user_session_path %></li>
    <% end %>
    <li><%= link_to "〇ホーム", dogs_path %></li>
   </ul>
</div>

<div class="water">

   <%= image_tag 'LOGO.png', class:'LOGO' %>

</div>

　　
</div>



  

  





   


app/views/dogs/new.html.erb
<h1>(Happy Harbs🌿)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @dog do |f| %>

<div class="post-container"> 

 <p class="title">投稿フォーム</p>

  <%= f.label :youtube_url %>
    <%= f.text_field :youtube_url, :size => 140 %>

    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

    <div class="field">
    <%= f.label :投稿 %>
    <%= f.text_area :body, :size => "30x2" %>
  </div>

  <%= f.submit "投稿する" %>
  <% end %>
</div>

<%= link_to "一覧に戻る", dogs_path %>




    

app/views/dogs/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="dog">
  <p><%= @dog.body %></p>
  <p><%= @dog.created_at %></p>
  <%= image_tag @dog.image_url, size: "250x200" if @dog.image? %>

  <% if @dog.youtube_url.present? %>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(@dog.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <% end %>

  <% @dog.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@dog) %>
        <%= link_to dog_like_path(@dog), method: :delete do %>
            <i class="fas fa-heart"></i><%= @dog.likes.count %>
        <% end %>
      <% else %>
        <%= link_to dog_likes_path(@dog), method: :post do %>
            <i class="far fa-heart"></i><%= @dog.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @dog.likes.count %>
    <% end %>
    <%= link_to "編集する", edit_dog_path(@dog.id) %>
    
</div>

<h2>いいねしたユーザー</h2>
<% @dog.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@dog, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>


<%= link_to "Dog一覧に戻る", dogs_path %>

app/views/perfumes/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>Perfu_me</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", perfumes_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_perfume_path, class: "link" %>
        </div>
    </body>

app/views/perfumes/show.html.erb
<div class="intoro">
<h5>診断結果</h5>
<p>あなたにおすすめの香りは…</p>
</div>
<div class="tweet-container">
<div class="tweet">

<div class="lemon">
    <% if @perfume.question == "1111" %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>
</div>

    <% elsif @perfume.question == "1112" %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>

    <% elsif @perfume.question == "1121" %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>

    <% elsif @perfume.question == "1122" %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>

    <% elsif @perfume.question == "1211" %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>

    <% elsif @perfume.question == "1212" %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>

    <% elsif @perfume.question == "1221" %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>

    <% elsif @perfume.question == "1222" %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

    <% elsif @perfume.question == "2111" %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>

    <% elsif @perfume.question == "2112" %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>

    <% elsif @perfume.question == "2121" %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>

    <% elsif @perfume.question == "2122" %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>

    <% elsif @perfume.question == "2211" %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>

    <% elsif @perfume.question == "2212" %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>

    <% elsif @perfume.question == "2221" %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>

    <% elsif @perfume.question == "2222" %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>


    <% end %>

    <h15>もどる</h15>
    <%= link_to 'Back', dogs_path %>


</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.dogs.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_dogs.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
<!-- ここまで-->

<%= link_to "Tweet一覧に戻る", dogs_path %>